# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ainimei' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ainimei
pod 'AFNetworking'
pod 'SDWebImage'
pod 'YYModel'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'Masonry'

end
